### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by HoLue** [alexismailov2/OIYolo#1]

**Comment by alexismailov2** [comment]
Hi Holger,

Yeah I am very upset but freelancer.com kiked me out by some undefined reason.
They said that I have broken their terms of usage and sure I could not gotten your money…

But you can ask me if you have questions since it is caused by my problems not your…

Thanks,
Oleksandr

Sent from Proton Mail for iOS

В EE, MMM d, yyyy в HH:mm, HoLue ***@***.***(mailto:В EE, MMM d, yyyy в HH:mm, HoLue <<a href=)> написал(а):

**Comment by alexismailov2** [comment]
Give me your mail and I will be able to help

**Comment by HoLue** [comment]
Hi Oleksandr,

Thanks for your fast positive response!!

As I don't like to have my email in the net, please just answer to the following trash email:
angenehmtraumhafterschwan@knickerbockerban.de
Then I will answer with my real email. Hope this is ok....


Best
Holger

PS: I tried to send this via email on Froday via github... but this did not go through..., just recogniced this, now.

**Comment by alexismailov2** [comment]
Fixed
